-- Run this once in Supabase SQL Editor.
create extension if not exists "pgcrypto";
create type public.team_role as enum ('owner','staff','bookkeeper');
create type public.invoice_status as enum ('draft','sent','paid','overdue','void');
create type public.transaction_type as enum ('payment','expense','refund');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, role public.team_role not null default 'staff', created_at timestamptz not null default now());
create table public.clients (id uuid primary key default gen_random_uuid(), name text not null, email text, phone text, company text, billing_address text, notes text, created_by uuid references public.profiles(id), created_at timestamptz not null default now());
create table public.projects (id uuid primary key default gen_random_uuid(), slug text unique not null, title text not null, summary text, description text, live_url text, cover_url text, video_url text, technologies text[] default '{}', published boolean not null default false, sort_order integer default 0, created_by uuid references public.profiles(id), created_at timestamptz not null default now());
create table public.invoices (id uuid primary key default gen_random_uuid(), invoice_number text unique not null, client_id uuid references public.clients(id), status public.invoice_status not null default 'draft', issue_date date not null default current_date, due_date date, currency text not null default 'usd', subtotal_cents integer not null default 0 check(subtotal_cents>=0), tax_cents integer not null default 0 check(tax_cents>=0), total_cents integer not null default 0 check(total_cents>=0), notes text, stripe_checkout_session_id text, stripe_payment_intent_id text, created_by uuid references public.profiles(id), created_at timestamptz not null default now());
create table public.invoice_items (id uuid primary key default gen_random_uuid(), invoice_id uuid not null references public.invoices(id) on delete cascade, description text not null, quantity numeric(10,2) not null default 1, unit_price_cents integer not null check(unit_price_cents>=0), sort_order integer default 0);
create table public.transactions (id uuid primary key default gen_random_uuid(), type public.transaction_type not null, client_id uuid references public.clients(id), invoice_id uuid references public.invoices(id), amount_cents integer not null check(amount_cents>=0), currency text not null default 'usd', method text not null default 'manual', reference text, stripe_payment_intent_id text, occurred_at timestamptz not null default now(), notes text, created_by uuid references public.profiles(id), created_at timestamptz not null default now());
create table public.expenses (id uuid primary key default gen_random_uuid(), category text not null, vendor text, amount_cents integer not null check(amount_cents>=0), expense_date date not null default current_date, receipt_url text, deductible boolean default true, notes text, created_by uuid references public.profiles(id), created_at timestamptz not null default now());
create table public.refunds (id uuid primary key default gen_random_uuid(), transaction_id uuid references public.transactions(id), amount_cents integer not null check(amount_cents>0), reason text, stripe_refund_id text, status text not null default 'pending', created_by uuid references public.profiles(id), created_at timestamptz not null default now());

alter table public.profiles enable row level security; alter table public.clients enable row level security; alter table public.projects enable row level security; alter table public.invoices enable row level security; alter table public.invoice_items enable row level security; alter table public.transactions enable row level security; alter table public.expenses enable row level security; alter table public.refunds enable row level security;
create policy "team reads profiles" on public.profiles for select to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid()));
create policy "owner manages profiles" on public.profiles for all to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='owner')) with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='owner'));
create policy "public reads published projects" on public.projects for select using (published=true or exists(select 1 from public.profiles p where p.id=auth.uid()));
create policy "team manages projects" on public.projects for all to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid())) with check (exists(select 1 from public.profiles p where p.id=auth.uid()));

do $$ declare t text; begin foreach t in array array['clients','invoices','invoice_items','transactions','expenses','refunds'] loop execute format('create policy "team reads %1$s" on public.%1$I for select to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid()))',t); execute format('create policy "team writes %1$s" on public.%1$I for all to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid())) with check (exists(select 1 from public.profiles p where p.id=auth.uid()))',t); end loop; end $$;

create index invoices_client_idx on public.invoices(client_id); create index transactions_invoice_idx on public.transactions(invoice_id); create index expenses_date_idx on public.expenses(expense_date desc); create index projects_published_idx on public.projects(published,sort_order);

-- After creating your own Supabase user, make yourself owner:
-- insert into public.profiles(id,full_name,role) values ('YOUR_AUTH_USER_UUID','Allen','owner');
