import DemoGallery from "./DemoGallery";

export const metadata={title:"Interactive Work | Vong Digital Works",description:"Explore working website concepts across real estate, fitness, hospitality, and ecommerce, designed and developed by Vong Digital Works."};

export default function Showcase(){return <main className="showcasePage">
  <div className="showcaseTop"><div className="shell"><a href="mailto:contact@vongdigitalworks.com">contact@vongdigitalworks.com</a><span>DESIGN · DEVELOPMENT · BUSINESS SYSTEMS</span></div></div>
  <nav className="nav shell"><a className="brand" href="/"><span>V</span> VONG / DIGITAL WORKS</a><div className="showcaseNav"><a href="#work">Selected work</a><a href="#standards">What I build</a><a href="/pricing">Pricing</a></div><a className="navCta" href="/#contact">Start a project ↗</a></nav>
  <section className="showcaseHero shell"><p className="kicker">Working portfolio / 2026</p><h1>Designed to impress.<br/><em>Built to perform.</em></h1><div><p>Every concept below is a working customer journey—not a flat screenshot. Browse collections, open details, use navigation, test forms, and see how thoughtful design supports a real business goal.</p><a href="#work">Explore the projects ↓</a></div></section>
  <section className="showcaseProof"><div className="shell"><article><b>04</b><span>Interactive industries</span></article><article><b>100%</b><span>Responsive experiences</span></article><article><b>FULL STACK</b><span>Design through deployment</span></article></div></section>
  <section className="shell showcaseContent" id="work"><div className="workIntro"><p>SELECTED CONCEPTS</p><h2>Choose an industry.<br/>Then click around.</h2><p>Each demo shows a different visual direction and conversion path. They are portfolio concepts, not template packages—your project would be designed around your own brand and customers.</p></div><DemoGallery/></section>
  <section className="showcaseStandards" id="standards"><div className="shell"><p>WHAT EVERY BUILD CAN INCLUDE</p><h2>A polished website is only the beginning.</h2><div><article><span>01</span><h3>Strategy + content structure</h3><p>Clear priorities, useful page flow, and calls to action aligned with how customers decide.</p></article><article><span>02</span><h3>Responsive custom design</h3><p>A distinct visual system that stays readable, fast, and easy to use on phones and desktops.</p></article><article><span>03</span><h3>Real business functionality</h3><p>Secure forms, accounts, databases, payments, dashboards, integrations, and custom workflows.</p></article><article><span>04</span><h3>Launch + ownership</h3><p>Deployment, domain setup, analytics-ready foundations, and portable source code you control.</p></article></div></div></section>
  <section className="showcaseCta"><div className="shell"><p>HAVE A PROJECT IN MIND?</p><h2>Let&apos;s build the experience<br/>your business deserves.</h2><div><a className="button darkButton" href="/#contact">Start a project ↗</a><a href="mailto:contact@vongdigitalworks.com">contact@vongdigitalworks.com ↗</a></div></div></section>
</main>}
