import InquiryForm from "./InquiryForm";

const services = [
  { number: "01", title: "Custom websites", text: "Purpose-built websites shaped around your brand, audience, and business goals—not squeezed into a template." },
  { number: "02", title: "Frontend development", text: "Fast, responsive interfaces with thoughtful motion, clear content, and a polished experience on every screen." },
  { number: "03", title: "Backend systems", text: "Secure databases, dashboards, authentication, APIs, payments, and the behind-the-scenes tools your business needs." },
];

export default function Home() {
  return <main>
    <nav className="nav shell" aria-label="Primary navigation">
      <a className="brand" href="#top" aria-label="Vong Digital Works home"><span>V</span> VONG / DIGITAL WORKS</a>
      <div className="navLinks"><a href="/showcase">Explore work</a><a href="#services">Services</a><a href="#process">Process</a><a href="/login">Client login</a></div>
      <a className="navCta" href="#contact">Start a project <span>↗</span></a>
    </nav>

    <section className="impactHero" id="top">
      <div className="shell impactIntro"><div><div className="heroEyebrow"><i /> Independent full-stack web studio</div><h1>I build websites<br/>people <em>remember.</em></h1></div><div className="impactPitch"><p>Custom design on the surface. Powerful systems underneath. Every project is built to stand out and move your business forward.</p><div className="heroActions"><a className="button primary" href="/showcase">Explore the work <span>↗</span></a><a className="textLink" href="#contact">Start a project</a></div></div></div>
      <div className="heroReel" aria-label="Featured website concept previews">
        <a className="reelCard reelEstate" href="#range"><img src="/concept-estate.png" alt="Luxury real estate website concept"/><div className="reelChrome"><i/><i/><i/><span>vanta.properties</span></div><div className="reelCopy"><small>01 / REAL ESTATE</small><b>RARE SPACE.<br/>EXACTLY PLACED.</b><span>EXPLORE CONCEPT ↗</span></div></a>
        <a className="reelCard reelFitness" href="#range"><img src="/concept-fitness.png" alt="Fitness coaching platform concept"/><div className="reelChrome"><i/><i/><i/><span>forge.system</span></div><div className="reelCopy"><small>02 / FITNESS PLATFORM</small><b>OUTWORK<br/>YESTERDAY.</b><span>VIEW BUILD ↗</span></div></a>
        <a className="reelCard reelLex" href="https://lexautoworks.com/" target="_blank" rel="noreferrer"><div className="reelChrome"><i/><i/><i/><span>lexautoworks.com</span></div><div className="reelLexInner"><small>LIVE CLIENT PROJECT</small><b>LEX<br/>AUTO WORK</b><p>TOYOTA + LEXUS SPECIALIST</p><div><span>F SPORT</span><span>2UR V8</span><span>HYBRID</span></div></div><label>VIEW LIVE WEBSITE ↗</label></a>
        <a className="reelCard reelRestaurant" href="#range"><img src="/concept-restaurant.png" alt="Premium restaurant website concept"/><div className="reelChrome"><i/><i/><i/><span>kodo.openfire</span></div><div className="reelCopy"><small>03 / HOSPITALITY</small><b>CONTROL<br/>THE FLAME.</b><span>RESERVE A TABLE ↗</span></div></a>
        <a className="reelCard reelCommerce" href="#range"><img src="/concept-commerce.png" alt="Technology ecommerce website concept"/><div className="reelChrome"><i/><i/><i/><span>vector.audio</span></div><div className="reelCopy right"><small>04 / ECOMMERCE</small><b>PURE<br/>SIGNAL.</b><span>SHOP THE SYSTEM ↗</span></div></a>
        <a className="reelCard reelMedical" href="#range"><img src="/concept-medical.png" alt="Advanced healthcare website concept"/><div className="reelChrome"><i/><i/><i/><span>nexus.health</span></div><div className="reelCopy"><small>05 / HEALTHCARE</small><b>CARE,<br/>ENGINEERED.</b><span>BOOK CONSULTATION ↗</span></div></a>
      </div>
      <div className="wallTicker"><span>STRATEGY</span><i>✦</i><span>DESIGN</span><i>✦</i><span>FRONTEND</span><i>✦</i><span>BACKEND</span><i>✦</i><span>LAUNCH</span></div>
    </section>

    <section className="engineeringProof"><div className="shell"><div className="proofHeader"><p>ENGINEERING CAPABILITY / 2026</p><span>ALL SYSTEMS OPERATIONAL <i/></span></div><div className="proofGrid"><article><small>01 / EXPERIENCE</small><b>Interfaces that don&apos;t<br/>look templated.</b><p>Custom art direction, responsive systems, motion, interaction, and accessibility engineered around the brand.</p></article><article><small>02 / ARCHITECTURE</small><b>Real systems behind<br/>the visuals.</b><p>Authentication, databases, dashboards, APIs, payments, invoices, automation, and deployment—not just a landing page.</p></article><article><small>03 / OWNERSHIP</small><b>Source code you<br/>actually control.</b><p>Portable builds prepared for GitHub, Render, Supabase, Stripe, and the next phase of your business.</p></article></div></div></section>

    <section className="rangeSection" id="range"><div className="shell rangeHead"><div><p className="kicker">Concept range / AI reference visuals</p><h2>Any industry.<br/>No repeated formula.</h2></div><p>Every box below explores a different audience, business model, visual language, and technical challenge. These concepts show the range we can build; Lex Auto Work is the featured live client project.</p></div><div className="rangeGrid">
      <article className="rangeCard rangeLex"><div className="rangeMedia lexMedia"><div className="lexHud"><small>LIVE CLIENT PROJECT</small><b>LEX<br/>AUTO WORK</b><span>TOYOTA + LEXUS SPECIALIST</span></div></div><div className="rangeInfo"><span>01 / AUTOMOTIVE</span><h3>Service booking + performance brand</h3><p>Conversion-focused service pages, specialty positioning, build galleries, pricing, and direct booking.</p><a href="https://lexautoworks.com/" target="_blank" rel="noreferrer">VIEW LIVE WEBSITE ↗</a></div></article>
      <article className="rangeCard rangeEstate"><div className="rangeMedia"><img src="/concept-estate.png" alt="AI-generated luxury real estate website concept"/><div className="screenOverlay"><small>VANTA / PROPERTIES</small><b>RARE SPACE.<br/>EXACTLY PLACED.</b><span>EXPLORE RESIDENCES →</span></div></div><div className="rangeInfo"><span>02 / REAL ESTATE</span><h3>Luxury listings + lead capture</h3><p>Property search, cinematic listings, agent profiles, saved homes, inquiry routing, and private tours.</p><a href="/showcase">EXPLORE CONCEPT ↗</a></div></article>
      <article className="rangeCard"><div className="rangeMedia"><img src="/concept-fitness.png" alt="AI-generated fitness coaching website concept"/><div className="screenOverlay lower"><small>FORGE / SYSTEM</small><b>OUTWORK<br/>YESTERDAY.</b><span>START TRAINING →</span></div></div><div className="rangeInfo"><span>03 / FITNESS</span><h3>Coaching + member platform</h3><p>Programs, memberships, client progress, payments, scheduling, exercise libraries, and coach dashboards.</p><a href="/showcase">EXPLORE CONCEPT ↗</a></div></article>
      <article className="rangeCard rangeWide"><div className="rangeMedia"><img src="/concept-restaurant.png" alt="AI-generated premium restaurant website concept"/><div className="screenOverlay restaurantCopy"><small>KODO / OPEN FIRE</small><b>CONTROL<br/>THE FLAME.</b><span>RESERVE YOUR TABLE →</span></div></div><div className="rangeInfo"><span>04 / HOSPITALITY</span><h3>Restaurant + reservation experience</h3><p>Story-driven menus, reservations, private events, location management, gift cards, and seasonal campaigns.</p><a href="/showcase">EXPLORE CONCEPT ↗</a></div></article>
      <article className="rangeCard"><div className="rangeMedia"><img src="/concept-commerce.png" alt="AI-generated technology ecommerce website concept"/><div className="screenOverlay productCopy"><small>VECTOR / AUDIO</small><b>PURE<br/>SIGNAL.</b><span>ADD TO SYSTEM — $349</span></div></div><div className="rangeInfo"><span>05 / ECOMMERCE</span><h3>Products + frictionless checkout</h3><p>Product discovery, inventory, subscriptions, bundles, secure checkout, customer accounts, and fulfillment.</p><a href="/showcase">EXPLORE CONCEPT ↗</a></div></article>
      <article className="rangeCard rangeSaas"><div className="rangeMedia saasMedia"><header><b>APEX / OS</b><span>LIVE DATA <i/></span></header><div className="saasBig"><small>REVENUE OPERATIONS</small><b>$2.84M</b><div className="saasGraph"><i/><i/><i/><i/><i/><i/><i/><i/></div></div><div className="saasStats"><span><b>+38%</b> GROWTH</span><span><b>98.2%</b> UPTIME</span></div></div><div className="rangeInfo"><span>06 / SaaS</span><h3>Software + business intelligence</h3><p>Authentication, subscriptions, data dashboards, team roles, workflows, reports, alerts, and API integrations.</p><a href="/showcase">EXPLORE CONCEPT ↗</a></div></article>
      <article className="rangeCard rangeWide"><div className="rangeMedia"><img src="/concept-medical.png" alt="AI-generated advanced healthcare website concept"/><div className="screenOverlay medicalCopy"><small>NEXUS / HEALTH</small><b>CARE,<br/>ENGINEERED.</b><span>BOOK A CONSULTATION →</span></div></div><div className="rangeInfo"><span>07 / HEALTHCARE</span><h3>Patient access + secure operations</h3><p>Provider search, scheduling, service education, intake workflows, secure portals, and accessible UX.</p><a href="/showcase">EXPLORE CONCEPT ↗</a></div></article>
      <article className="rangeCard rangeService"><div className="rangeMedia serviceMedia"><span>STRATEGY / LAW / FINANCE</span><b>TRUST IS<br/>BUILT IN<br/>THE DETAILS.</b><div><i>01</i><p>Clear authority</p><i>02</i><p>Qualified leads</p><i>03</i><p>Secure intake</p></div></div><div className="rangeInfo"><span>08 / PROFESSIONAL SERVICES</span><h3>Authority + qualified lead generation</h3><p>Professional positioning, case studies, secure intake, appointment booking, document flows, and CRM routing.</p><a href="/showcase">EXPLORE CONCEPT ↗</a></div></article>
    </div></section>

    <section className="statement"><div className="shell statementGrid"><p className="kicker">What I do</p><h2>More than a good-looking website. I build complete digital experiences that <em>work hard</em> for your business.</h2></div></section>

    <section className="services" id="services"><div className="shell"><div className="sectionHead light"><div><p className="kicker">Capabilities</p><h2>From first sketch<br/>to full-stack launch.</h2></div><p className="sideCopy">One collaborative partner for strategy, design, development, and the technical systems behind it all.</p></div>
      <div className="serviceList">{services.map(service => <article key={service.number}><span>{service.number}</span><h3>{service.title}</h3><p>{service.text}</p><b>↗</b></article>)}</div>
    </div></section>

    <section className="section process shell" id="process"><p className="kicker">How we work together</p><div className="processIntro"><h2>Clear communication.<br/>No mystery.</h2><p>You stay involved from beginning to end. I explain the decisions, share progress often, and build around what your business actually needs.</p></div>
      <div className="steps"><div><span>01</span><h3>Discover</h3><p>We define your goals, users, features, timeline, and what success looks like.</p></div><div><span>02</span><h3>Design</h3><p>I shape the structure and visual direction, then refine it with your feedback.</p></div><div><span>03</span><h3>Build</h3><p>I develop the frontend and backend, test the experience, and keep you updated.</p></div><div><span>04</span><h3>Launch</h3><p>We go live confidently, with support for the next stage of growth.</p></div></div>
    </section>

    <section className="contact" id="contact"><div className="shell contactGrid"><div><p className="kicker">Start a conversation</p><h2>Have an idea?<br/><em>Let&apos;s build it.</em></h2><p className="contactLead">Tell me what you&apos;re working on, even if it&apos;s still just an idea. I&apos;ll help you figure out the best next step.</p><div className="contactMethods"><span>Email and phone details can be added here when ready.</span></div></div>
      <InquiryForm />
    </div></section>
    <footer className="footer"><div className="shell"><a className="brand" href="#top"><span>V</span> VONG / DIGITAL WORKS</a><p>Custom websites. Complete builds. Real collaboration.</p><div><a href="/login">Client login</a> · <a href="/dashboard">Business dashboard</a> · <a href="#top">Back to top ↑</a></div></div></footer>
  </main>;
}
