"use client";
import { FormEvent, useEffect, useState } from "react";
export default function ResetPasswordForm(){
  const [token,setToken]=useState("");const [error,setError]=useState("");const [done,setDone]=useState(false);const [loading,setLoading]=useState(false);
  useEffect(()=>{const hash=new URLSearchParams(location.hash.slice(1));setToken(hash.get("access_token")||"");const message=hash.get("error_description");if(message)setError(decodeURIComponent(message))},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const form=new FormData(event.currentTarget);const password=String(form.get("password")||"");const confirm=String(form.get("confirm")||"");if(password.length<8){setError("Use at least 8 characters.");return}if(password!==confirm){setError("Passwords do not match.");return}if(!token){setError("This recovery link is missing or expired. Request a new one.");return}setLoading(true);const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key){setError("Password recovery is not configured.");setLoading(false);return}const response=await fetch(`${url}/auth/v1/user`,{method:"PUT",headers:{apikey:key,Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({password})});const payload=await response.json();if(!response.ok){setError(payload.msg||payload.error_description||"Unable to update password. Request a new link.");setLoading(false);return}setDone(true)}
  if(done)return <section className="loginCard"><a className="brand" href="/"><span>V</span> VONG / DIGITAL WORKS</a><p className="kicker">Password updated</p><h1>Your account<br/>is ready.</h1><p style={{color:"var(--muted)",lineHeight:1.6,margin:0}}>You can now sign in to your private customer workspace.</p><a className="dashAdd" href="/login">Continue to sign in →</a></section>;
  return <form className="loginCard" onSubmit={submit}><a className="brand" href="/"><span>V</span> VONG / DIGITAL WORKS</a><p className="kicker">Secure account recovery</p><h1>Create a new<br/>password.</h1><label>New password<input name="password" type="password" minLength={8} required autoComplete="new-password"/></label><label>Confirm password<input name="confirm" type="password" minLength={8} required autoComplete="new-password"/></label>{error&&<p className="loginError">{error}</p>}<button className="dashAdd" disabled={loading}>{loading?"Updating…":"Update password →"}</button><small>Use at least eight characters and do not reuse a password from another account.</small></form>
}
